import { colors } from '../../components/Colors';

const data = [
  {
    id: 1,
    content: 'AC',
    value: 'AC',
    icon: false,
    colorText: colors.black,
    color: colors.gray,
  },
  {
    id: 2,
    content: '(  )',
    value: '( )',
    icon: false,
    colorText: colors.black,
    color: colors.gray,
  },
  {
    id: 3,
    content: '%',
    value: '%',
    icon: false,
    colorText: colors.black,
    color: colors.gray,
  },
  {
    id: 4,
    content: '÷',
    value: '÷',
    icon: false,
    colorText: colors.white,
    color: colors.red,
  },
  {
    id: 5,
    content: '7',
    value: 7,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 6,
    content: '8',
    value: 8,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 7,
    content: '9',
    value: 9,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 8,
    content: '×',
    value: '×',
    icon: false,
    colorText: colors.white,
    color: colors.red,
  },
  {
    id: 9,
    content: '4',
    value: 4,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 10,
    content: '5',
    value: 5,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 11,
    content: '6',
    value: 6,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 12,
    content: '-',
    value: '-',
    icon: false,
    colorText: colors.white,
    color: colors.red,
  },
  {
    id: 13,
    content: '1',
    value: 1,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 14,
    content: '2',
    value: 2,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 15,
    content: '3',
    value: 3,
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 16,
    content: '+',
    value: '+',
    icon: false,
    colorText: colors.white,
    color: colors.red,
  },
  {
    id: 17,
    content: '0',
    value: 'AC',
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 18,
    content: ',',
    value: 'AC',
    icon: false,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 19,
    content: 'AC',
    value: 'AC',
    icon: true,
    colorText: colors.white,
    color: colors.darkGray,
  },
  {
    id: 20,
    content: '=',
    value: '=',
    icon: false,
    colorText: colors.white,
    color: colors.red,
  },
]

export { data }